version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "2000:2000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/usr/src/app
    command: nodemon .
    depends_on:
      - db
      - redis
    networks:
      - default

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/usr/src/app
    command: npm start
    networks:
      - default

  db:
    image: mysql:8
    env_file:
      - ./api/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
      MYSQL_DATABASE: ${DEV_DB_DATABASE}
      MYSQL_USER: ${DEV_DB_USERNAME}
      MYSQL_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:alpine
    env_file:
      - ./api/.env
    ports:
      - "6379:6379"
    networks:
      - default

volumes:
  db_data:

networks:
  default:
    external:
      name: portfoliohub_default